import { Employee, EmployeeUpdate } from '@/lib/types/employee/index';

export const getEmployeeFormData = (data: Employee): EmployeeUpdate => {
  const {
    firstName,
    lastName,
    gender,
    dateOfJoining,
    dob,
    photo,
    nationalId,
    phone,
    email,
    presentAddress,
    permanentAddress,
    maritalStatus,
    emergencyContactName,
    emergencyContactRelation,
    emergencyContactPhone,

    lineManagerId,
    jobTitle,
    employeeSerialId,
    passportNumber,
    drivingLicenseNumber,
    tinNumber,
    officePhone,
    officeEmail,
    estimatedConfirmationDate,
    actualConfirmationDate,
    displayName,
    deviceUserId,
    grossSalary,
    birthCertificateNumber,

    // Relations
    employeeTypeId,
    probationDurationId,
    gradeId,
    designationId,
    paymentTypeId,
    companyId,
    businessUnitId,
    workplaceGroupId,
    workPlaceId,
    departmentId,
    teamId,
    bloodGroupId,
    nationalityId,
    religionId,
    roleId,
    supervisorId,
  } = data;
  return {
    firstName,
    lastName,
    gender,
    dateOfJoining,
    dob,
    photo,
    nationalId,
    phone,
    email,
    presentAddress,
    permanentAddress,
    maritalStatus,
    emergencyContactName,
    emergencyContactRelation,
    emergencyContactPhone,

    lineManagerId,
    jobTitle,
    employeeSerialId,
    passportNumber,
    drivingLicenseNumber,
    tinNumber,
    officePhone,
    officeEmail,
    estimatedConfirmationDate,
    actualConfirmationDate,
    displayName,
    deviceUserId,
    grossSalary,
    birthCertificateNumber,
    // relations
    employeeTypeId: employeeTypeId?.toString() ?? '',
    probationDurationId: probationDurationId?.id?.toString() ?? '',
    gradeId: gradeId?.toString() ?? '',
    designationId: designationId?.toString() ?? '',
    paymentTypeId: paymentTypeId?.id?.toString() ?? '',
    companyId: companyId?.toString() ?? '',
    businessUnitId: businessUnitId?.toString() ?? '',
    workplaceGroupId: workplaceGroupId?.toString() ?? '',
    workPlaceId: workPlaceId?.toString() ?? '',
    departmentId: departmentId?.toString() ?? '',
    teamId: teamId?.toString() ?? '',
    bloodGroupId: bloodGroupId?.id?.toString() ?? '',
    nationalityId: nationalityId?.id?.toString() ?? '',
    religionId: religionId?.id?.toString() ?? '',
    roleId: roleId?.toString() ?? '',
    supervisorId: supervisorId?.toString() ?? '',

    // religionId": 1,
    // "nationalityId":1,
    // "bloodGroupId": 1,
    // "paymentTypeId":1,
    // "probationDurationId":1,
    // "birthCertificateNumber": null,
    // "passportNumber": "54321",
    // "drivingLicenseNumber": "8888",
    // "tinNumber": "09876",
    // "officePhone": "099877655454",
    // "officeEmail": "office@email.com",
    // "estimatedConfirmationDate": "2025-09-28T10:30:00",
    // "actualConfirmationDate": "2025-09-28T10:30:00"
    // }
  };
};
export const getEmployeeApiData = (data: EmployeeUpdate): EmployeeUpdate => {
  const {
    firstName,
    lastName,
    gender,
    dateOfJoining,
    dob,
    photo,
    nationalId,
    phone,
    email,
    presentAddress,
    permanentAddress,
    maritalStatus,
    emergencyContactName,
    emergencyContactRelation,
    emergencyContactPhone,
    lineManagerId,
    jobTitle,
    employeeSerialId,
    passportNumber,
    drivingLicenseNumber,
    tinNumber,
    officePhone,
    officeEmail,
    estimatedConfirmationDate,
    actualConfirmationDate,
    displayName,
    deviceUserId,
    grossSalary,
    birthCertificateNumber,

    // Relations
    employeeTypeId,
    probationDurationId,
    gradeId,
    designationId,
    paymentTypeId,
    companyId,
    businessUnitId,
    workplaceGroupId,
    workPlaceId,
    departmentId,
    teamId,
    bloodGroupId,
    nationalityId,
    religionId,
    roleId,
    supervisorId,
  } = data;

  return {
    firstName,
    lastName,
    gender,
    dateOfJoining,
    dob,
    photo,
    nationalId,
    phone,
    email,
    presentAddress,
    permanentAddress,
    maritalStatus,
    emergencyContactName,
    emergencyContactRelation,
    emergencyContactPhone,
    lineManagerId,
    jobTitle,
    employeeSerialId,
    passportNumber,
    drivingLicenseNumber,
    tinNumber,
    officePhone,
    officeEmail,
    estimatedConfirmationDate,
    actualConfirmationDate,
    displayName,
    deviceUserId,
    grossSalary,
    birthCertificateNumber,
    employeeTypeId: employeeTypeId ? Number(employeeTypeId) : null,
    probationDurationId: probationDurationId
      ? Number(probationDurationId)
      : null,
    gradeId: gradeId ? Number(gradeId) : null,
    designationId: designationId ? Number(designationId) : null,
    paymentTypeId: paymentTypeId ? Number(paymentTypeId) : null,
    companyId: companyId ? Number(companyId) : null,
    businessUnitId: businessUnitId ? Number(businessUnitId) : null,
    workplaceGroupId: workplaceGroupId ? Number(workplaceGroupId) : null,
    workPlaceId: workPlaceId ? Number(workPlaceId) : null,
    departmentId: departmentId ? Number(departmentId) : null,
    teamId: teamId ? Number(teamId) : null,
    bloodGroupId: bloodGroupId ? Number(bloodGroupId) : null,
    nationalityId: nationalityId ? Number(nationalityId) : null,
    religionId: religionId ? Number(religionId) : null,
    roleId: roleId ? Number(roleId) : null,
    supervisorId: supervisorId ? Number(supervisorId) : null,
  };
};
